<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAuw2gnm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAuw2gnm/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAuw2gnm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAuw2gnm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAuw2gnm\appProdProjectContainer([
    'container.build_hash' => 'Auw2gnm',
    'container.build_id' => '1505bd91',
    'container.build_time' => 1671013345,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAuw2gnm');
