<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOodr0qd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOodr0qd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOodr0qd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOodr0qd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerOodr0qd\appDevDebugProjectContainer([
    'container.build_hash' => 'Oodr0qd',
    'container.build_id' => '3938a5d3',
    'container.build_time' => 1671694358,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOodr0qd');
